//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseGuide.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Code {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Code() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LicenseGuide.Resources.Code", typeof(Code).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPL family of software licenses has as its main goal to legally prevent the source code of a program from being kept from its users: they must be guaranteed the freedom to modify the programs they run, they argue. Therefore, it is essential that anyone who publishes a computer program that contains someone else&apos;s GPL-licensed source code must also make the entire source code of the entire program available to any end-user who requests it, including any source code they have written themselves, under the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string agpl_explanation {
            get {
                return ResourceManager.GetString("agpl_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU AFFERO GENERAL PUBLIC LICENSE
        ///                       Version 3, 19 November 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU Affero General Public License is a free, copyleft license for
        ///software and other kinds of works, specifically designed to ensure
        ///cooperation with the community in the case of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string agpl_full_text {
            get {
                return ResourceManager.GetString("agpl_full_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // SPDX-License-Identifier: AGPL-3.0-or-later
        ////* 
        /// * Copyright (c) [year] [your name]
        /// * 
        /// * This program is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU Affero General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// * 
        /// * This program is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABIL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string agpl_short_text {
            get {
                return ResourceManager.GetString("agpl_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU Affero General Public License (AGPL), version 3 or later.
        /// </summary>
        public static string agpl_title {
            get {
                return ResourceManager.GetString("agpl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For developers who want to release their source code freely with minimal headaches for potential code-receiving developers, a so-called permissive license is best, but one with certain terms and conditions. Many developers want to minimize hassle by waiving all rights and writing “do what you want”, but this can actually be counterproductive. In many countries it is not legally possible to completely waive all rights to your work, so if you are not clear, this can cause problems for those who want to use th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bsdpatent_explanation {
            get {
                return ResourceManager.GetString("bsdpatent_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) [year] [your name].  All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met:
        ///
        ///1. Redistributions of source code must retain the above copyright notice,
        ///   this list of conditions and the following disclaimer.
        ///
        ///2. Redistributions in binary form must reproduce the above copyright notice,
        ///   this list of conditions and the following disclaimer in the documentation
        ///   and/or other [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bsdpatent_full_text {
            get {
                return ResourceManager.GetString("bsdpatent_full_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // SPDX-License-Identifier: BSD-2-Clause-Patent
        ////* 
        /// * Copyright (c) [year] [your name]
        /// * 
        /// * Use of this source code is governed by a BSD-style
        /// * license that can be found in the LICENSE file or at
        /// * https://opensource.org/licenses/BSDplusPatent
        /// */.
        /// </summary>
        public static string bsdpatent_short_text {
            get {
                return ResourceManager.GetString("bsdpatent_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSD+Patent License, or BSD-2-Clause Plus Patent License.
        /// </summary>
        public static string bsdpatent_title {
            get {
                return ResourceManager.GetString("bsdpatent_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For full control, you should rely on the copyright that applies by default to all works that reach the threshold of originality. Almost all countries have signed agreements to enforce copyright laws with certain minimum protections, and to respect copyright in each other&apos;s countries. A creator of a work, such as a computer program, automatically has at least 50 years of exclusive economic and moral rights to determine how the work is copied and distributed, provided it is sufficiently original. As a general [rest of string was truncated]&quot;;.
        /// </summary>
        public static string copyright_explanation {
            get {
                return ResourceManager.GetString("copyright_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) [year] [your name]
        ///
        ///All rights reserved. No part of this software may be reproduced, distributed, or
        ///transmitted in any form or by any means whatsoever, including photocopying,
        ///recording, or other electronic or mechanical methods, without the prior written
        ///permission of the copyright holder, except in the case of brief quotations
        ///embodied in critical reviews and certain other noncommercial uses permitted by
        ///copyright law.
        ///
        ///THE SOURCE CODE FOR THIS SOFTWARE IS PROPRIETARY AND NOT LICEN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string copyright_full_text {
            get {
                return ResourceManager.GetString("copyright_full_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright (c) [year] [your name]. All rights reserved.
        /// * This source code is proprietary. Any unauthorized use
        /// * or distribution is strictly prohibited by copyright law.
        /// */.
        /// </summary>
        public static string copyright_short_text {
            get {
                return ResourceManager.GetString("copyright_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No License.
        /// </summary>
        public static string copyright_title {
            get {
                return ResourceManager.GetString("copyright_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be placed in a LICENSE or COPYRIGHT file or the like:.
        /// </summary>
        public static string full_text_label {
            get {
                return ResourceManager.GetString("full_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPL family of software licenses has as its main goal to legally prevent the source code of a program from being kept from its users: they must be guaranteed the freedom to modify the programs they run, they argue. Therefore, it is essential that anyone who publishes a computer program that contains someone else&apos;s GPL-licensed source code must also make the entire source code of the entire program available to any end-user who requests it, including any source code they have written themselves, under the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gpl2_explanation {
            get {
                return ResourceManager.GetString("gpl2_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU GENERAL PUBLIC LICENSE
        ///                       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intend [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gpl2_full_text {
            get {
                return ResourceManager.GetString("gpl2_full_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // SPDX-License-Identifier: GPL-2.0-or-later
        ////* 
        /// * Copyright (c) [year] [your name]
        /// * 
        /// * This program is free software; you can redistribute it and/or modify
        /// * it under the terms of the GNU General Public License as published by
        /// * the Free Software Foundation; either version 2 of the License, or
        /// * (at your option) any later version.
        /// * 
        /// * This program is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or F [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gpl2_short_text {
            get {
                return ResourceManager.GetString("gpl2_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU General Public License (GPL), version 2 or later.
        /// </summary>
        public static string gpl2_title {
            get {
                return ResourceManager.GetString("gpl2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPL family of software licenses has as its main goal to legally prevent the source code of a program from being kept from its users: they must be guaranteed the freedom to modify the programs they run, they argue. Therefore, it is essential that anyone who publishes a computer program that contains someone else&apos;s GPL-licensed source code must also make the entire source code of the entire program available to any end-user who requests it, including any source code they have written themselves, under the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gpl3_explanation {
            get {
                return ResourceManager.GetString("gpl3_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to take away your fre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gpl3_full_text {
            get {
                return ResourceManager.GetString("gpl3_full_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // SPDX-License-Identifier: GPL-3.0-or-later
        ////* 
        /// * Copyright (c) [year] [your name]
        /// * 
        /// * This program is free software: you can redistribute it and/or modify
        /// * it under the terms of the GNU General Public License as published by
        /// * the Free Software Foundation, either version 3 of the License, or
        /// * (at your option) any later version.
        /// * 
        /// * This program is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTABILITY or F [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gpl3_short_text {
            get {
                return ResourceManager.GetString("gpl3_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU General Public License (GPL), version 3 or later.
        /// </summary>
        public static string gpl3_title {
            get {
                return ResourceManager.GetString("gpl3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPL family of software licenses has as its main goal to legally prevent the source code of a program from being kept from its users: they must be guaranteed the freedom to modify the programs they run, they argue. In the main GPL licenses, it is therefore essential that anyone who publishes a computer program that contains someone else&apos;s GPL-licensed source code must also make the entire source code of the entire program available to any end-user who requests it, including any source code they have writ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lgpl_explanation {
            get {
                return ResourceManager.GetString("lgpl_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU LESSER GENERAL PUBLIC LICENSE
        ///                       Version 2.1, February 1999
        ///
        /// Copyright (C) 1991, 1999 Free Software Foundation, Inc.
        /// 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///[This is the first released version of the Lesser GPL.  It also counts
        /// as the successor of the GNU Library Public License, version 2, hence
        /// the version number 2.1.]
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lgpl_full_text {
            get {
                return ResourceManager.GetString("lgpl_full_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // SPDX-License-Identifier: LGPL-2.1-or-later
        ////* 
        /// * Copyright (c) [year] [your name]
        /// * 
        /// * This library is free software; you can redistribute it and/or
        /// * modify it under the terms of the GNU Lesser General Public
        /// * License as published by the Free Software Foundation; either
        /// * version 2.1 of the License, or (at your option) any later version.
        /// * 
        /// * This library is distributed in the hope that it will be useful,
        /// * but WITHOUT ANY WARRANTY; without even the implied warranty of
        /// * MERCHANTAB [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lgpl_short_text {
            get {
                return ResourceManager.GetString("lgpl_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU Lesser General Public License (LGPL), version 2.1 or later.
        /// </summary>
        public static string lgpl_title {
            get {
                return ResourceManager.GetString("lgpl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my source code to be distributed and come to use, even if that carries the risk of it ending up in closed source behind network services..
        /// </summary>
        public static string netservice_no {
            get {
                return ResourceManager.GetString("netservice_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise uses your source code as a subcomponent of software. Perhaps they have modified your source code, perhaps not. The software runs a network service for a legal purpose that you despise, and its users (e.g. customers or the public) interact with the software only over networks, i.e. it does not run directly on the users&apos; own computers. The service provider keeps all source code behind the software secret. Do you want this to be illegal?.
        /// </summary>
        public static string netservice_question {
            get {
                return ResourceManager.GetString("netservice_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in exchange for using my source code, I want them to be forced to make available to their end-users all the source code of the software that runs the service, including the source code that I did not write..
        /// </summary>
        public static string netservice_yes {
            get {
                return ResourceManager.GetString("netservice_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my source code to be distributed and come to use through a public agreement, even if it carries the risk that someone I despise might use or distribute the source code..
        /// </summary>
        public static string opensource_no {
            get {
                return ResourceManager.GetString("opensource_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise uses or distributes your source code without first having negotiated an agreement with you. Do you want this to be illegal?
        ///
        ///(&quot;Someone you despise&quot; can be a person or an organization, e.g. for-profit, political, military, religious, local or global. Please also imagine that they want to use your software for purposes that are legal but that you personally despise, e.g. commercially, for propaganda purposes, in war, in trade with dictatorships, etc.).
        /// </summary>
        public static string opensource_question {
            get {
                return ResourceManager.GetString("opensource_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want them to be forced to negotiate with me for the right to use or distribute my source code. I want to be able to decide who can use the source code, and make decisions on a case-by-case basis..
        /// </summary>
        public static string opensource_yes {
            get {
                return ResourceManager.GetString("opensource_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}:.
        /// </summary>
        public static string question_header {
            get {
                return ResourceManager.GetString("question_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example text which can be placed at the top of a source file (C/Java style):.
        /// </summary>
        public static string short_text_label {
            get {
                return ResourceManager.GetString("short_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my source code to be distributed and come to use, even if it carries the risk of it being used by closed source software..
        /// </summary>
        public static string strong_copyleft_no {
            get {
                return ResourceManager.GetString("strong_copyleft_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise makes and distributes software in binary (compiled) form. As a subcomponent, they use your source code. Perhaps they have modified your source code, perhaps not. They have not made the source code of their software available to the end-users of the software. Do you want this to be illegal?.
        /// </summary>
        public static string strong_copyleft_question {
            get {
                return ResourceManager.GetString("strong_copyleft_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in exchange for using my source code, I want software developers to be forced to make their own source code available to their end-users..
        /// </summary>
        public static string strong_copyleft_yes {
            get {
                return ResourceManager.GetString("strong_copyleft_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my source code to be distributed and come to use, even if it carries the risk of it being used to power proprietary hardware..
        /// </summary>
        public static string tivoization_no {
            get {
                return ResourceManager.GetString("tivoization_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise makes and distributes hardware for some particular group of end-users. To run the hardware, they use your source code as a subcomponent. Perhaps they have modified your source code, perhaps not. The source code of the software has been made available to anyone who wants it. However, the hardware is designed in such a way that an end-user is not able to compile and run that source code, not even unmodified source code. Do you want this to be illegal?.
        /// </summary>
        public static string tivoization_question {
            get {
                return ResourceManager.GetString("tivoization_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in exchange for using my source code, I want hardware manufacturers to be forced to allow their end-users to run self-compiled modified source code..
        /// </summary>
        public static string tivoization_yes {
            get {
                return ResourceManager.GetString("tivoization_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my source code to be distributed and come to use, as long as there is no risk to me personally..
        /// </summary>
        public static string weak_copyleft_no {
            get {
                return ResourceManager.GetString("weak_copyleft_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise makes and distributes software in binary (compiled) form. As a subcomponent, they use your source code, possibly modified, and have made your source code available to any end-user who wants it (with any modifications). However, they have not made their own source code available to all end-users who want it. It is also not possible for end-users of the Software to replace or modify your subcomponent of the Software. Do you want this to be illegal?.
        /// </summary>
        public static string weak_copyleft_question {
            get {
                return ResourceManager.GetString("weak_copyleft_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, they can keep their own source code closed, but in exchange for using my source code, I want the software developers to be forced to let their end-users replace and modify at least my subcomponent..
        /// </summary>
        public static string weak_copyleft_yes {
            get {
                return ResourceManager.GetString("weak_copyleft_yes", resourceCulture);
            }
        }
    }
}
