//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseGuide.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LicenseGuide.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my work to be distributed and come to use, even if it means the risk of not being acknowledged as the creator of the work..
        /// </summary>
        public static string attribution_no {
            get {
                return ResourceManager.GetString("attribution_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise uses or distributes your work. Nowhere do they state that you are the creator of the work. Do you want this to be illegal?.
        /// </summary>
        public static string attribution_question {
            get {
                return ResourceManager.GetString("attribution_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in exchange for using my work, I want them to be forced to acknowledge me as the creator of the work..
        /// </summary>
        public static string attribution_yes {
            get {
                return ResourceManager.GetString("attribution_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons family of public copyright licenses has the primary goal of promoting free culture and open content. That&apos;s why they have developed several licenses with careful legal language and varying terms, to allow creators who want to contribute to choose a license that suits their needs.
        ///
        ///Licensing your work as CC BY gives potential licensees — people interested in copying, using, modifying and distributing your work — the right to do so in ways that would otherwise violate copyright. However [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cc_by_explanation {
            get {
                return ResourceManager.GetString("cc_by_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title of work] © [year] by [your name] is licensed as CC BY 4.0. To view a copy of this license, visit: https://creativecommons.org/licenses/by/4.0/deed.sv.
        /// </summary>
        public static string cc_by_notice {
            get {
                return ResourceManager.GetString("cc_by_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons BY 4.0.
        /// </summary>
        public static string cc_by_title {
            get {
                return ResourceManager.GetString("cc_by_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons family of public copyright licenses has the primary goal of promoting free culture and open content. That&apos;s why they have developed several licenses with careful legal language and varying terms, to allow creators who want to contribute to choose a license that suits their needs.
        ///
        ///Licensing your work as CC BY-NC gives potential licensees — people interested in copying, using, modifying and distributing your work — the right to do so in ways that would otherwise violate copyright law.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cc_bync_explanation {
            get {
                return ResourceManager.GetString("cc_bync_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title of work] © [year] by [your name] is licensed as CC BY-NC 4.0. To view a copy of this license, visit: https://creativecommons.org/licenses/by-nc/4.0/deed.sv.
        /// </summary>
        public static string cc_bync_notice {
            get {
                return ResourceManager.GetString("cc_bync_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons BY-NC 4.0.
        /// </summary>
        public static string cc_bync_title {
            get {
                return ResourceManager.GetString("cc_bync_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons family of public copyright licenses has the primary goal of promoting free culture and open content. That&apos;s why they have developed several licenses with careful legal language and varying terms, to allow creators who want to contribute to choose a license that suits their needs.
        ///
        ///Licensing your work as CC BY-NC-ND gives potential licensees — people interested in copying, using and distributing your work — the right to do so in ways that would otherwise violate copyright law. However, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cc_byncnd_explanation {
            get {
                return ResourceManager.GetString("cc_byncnd_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title of work] © [year] by [your name] is licensed as CC BY-NC-ND 4.0. To view a copy of this license, visit: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.sv.
        /// </summary>
        public static string cc_byncnd_notice {
            get {
                return ResourceManager.GetString("cc_byncnd_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons BY-NC-ND 4.0.
        /// </summary>
        public static string cc_byncnd_title {
            get {
                return ResourceManager.GetString("cc_byncnd_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons family of public copyright licenses has the primary goal of promoting free culture and open content. That&apos;s why they have developed several licenses with careful legal language and varying terms, to allow creators who want to contribute to choose a license that suits their needs.
        ///
        ///Licensing your work as CC BY-NC-SA gives potential licensees — people interested in copying, using, modifying and distributing your work — the right to do so in ways that would otherwise violate copyright la [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cc_byncsa_explanation {
            get {
                return ResourceManager.GetString("cc_byncsa_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title of work] © [year] by [your name] is licensed as CC BY-NC-SA 4.0. To view a copy of this license, visit: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.sv.
        /// </summary>
        public static string cc_byncsa_notice {
            get {
                return ResourceManager.GetString("cc_byncsa_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons BY-NC-SA 4.0.
        /// </summary>
        public static string cc_byncsa_title {
            get {
                return ResourceManager.GetString("cc_byncsa_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons family of public copyright licenses has the primary goal of promoting free culture and open content. That&apos;s why they have developed several licenses with careful legal language and varying terms, to allow creators who want to contribute to choose a license that suits their needs.
        ///
        ///Licensing your work as CC BY-ND gives potential licensees — people interested in copying, using and distributing your work — the right to do so in ways that would otherwise violate copyright law. However, th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cc_bynd_explanation {
            get {
                return ResourceManager.GetString("cc_bynd_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title of work] © [year] by [your name] is licensed as CC BY-ND 4.0. To view a copy of this license, visit: https://creativecommons.org/licenses/by-nd/4.0/deed.sv.
        /// </summary>
        public static string cc_bynd_notice {
            get {
                return ResourceManager.GetString("cc_bynd_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons BY-ND 4.0.
        /// </summary>
        public static string cc_bynd_title {
            get {
                return ResourceManager.GetString("cc_bynd_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons family of public copyright licenses has the primary goal of promoting free culture and open content. That&apos;s why they have developed several licenses with careful legal language and varying terms, to allow creators who want to contribute to choose a license that suits their needs.
        ///
        ///Licensing your work as CC BY-SA gives potential licensees — people interested in copying, using, modifying and distributing your work — the right to do so in ways that would otherwise violate copyright law.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cc_bysa_explanation {
            get {
                return ResourceManager.GetString("cc_bysa_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title of work] © [year] by [your name] is licensed as CC BY-SA 4.0. To view a copy of this license, visit: https://creativecommons.org/licenses/by-sa/4.0/deed.sv.
        /// </summary>
        public static string cc_bysa_notice {
            get {
                return ResourceManager.GetString("cc_bysa_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons BY-SA 4.0.
        /// </summary>
        public static string cc_bysa_title {
            get {
                return ResourceManager.GetString("cc_bysa_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Creative Commons family of public copyright licenses has the primary goal of promoting free culture and open content. That&apos;s why they have developed several licenses with careful legal language and varying terms and conditions, to allow creators who want to contribute to choose a license that suits their needs.
        ///
        ///By licensing/marking your work as CC0, you indicate your intention to permanently waive all copyright, to the fullest extent permitted by law, without any requirement for compensation or attri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cc0_explanation {
            get {
                return ResourceManager.GetString("cc0_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [title of work] by [your name] is licensed/marked as CC0 1.0 Universal. To view a copy of this license, visit: https://creativecommons.org/publicdomain/zero/1.0/deed.sv.
        /// </summary>
        public static string cc0_notice {
            get {
                return ResourceManager.GetString("cc0_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC0 1.0 Universal.
        /// </summary>
        public static string cc0_title {
            get {
                return ResourceManager.GetString("cc0_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my work to be distributed and come to use through a public agreement, even if it carries the risk that someone I despise may use or distribute it..
        /// </summary>
        public static string copyright_no {
            get {
                return ResourceManager.GetString("copyright_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a creator of a work — a painting, novel, film, musical composition, scientific article, software documentation, photograph, architecture, choreography, technical drawing, sculpture, podcast recording, fashion design, or anything else protected by copyright.
        ///
        ///Suppose someone you despise uses or distributes your work without first having negotiated an agreement with you. Do you want this to be illegal?
        ///
        ///(“Someone you dislike” can be a person or an organization, such as for-profit, political, milit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string copyright_question {
            get {
                return ResourceManager.GetString("copyright_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want them to be forced to negotiate with me for the right to use or distribute my work. I want to be able to decide who gets to use the work, and make decisions on a case-by-case basis..
        /// </summary>
        public static string copyright_yes {
            get {
                return ResourceManager.GetString("copyright_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For full control, you should rely on the copyright that applies by default to all works that reach the threshold of originality. Almost all countries have signed agreements to enforce copyright laws with certain minimum protections, and to respect copyright in each other&apos;s countries. A creator of a work, such as a painting, novel, film, or musical composition, automatically has at least 50 years of exclusive economic and moral rights to determine how the work is copied and distributed, provided it is suffic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string full_copyright_explanation {
            get {
                return ResourceManager.GetString("full_copyright_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) [year] [your name]. All rights reserved..
        /// </summary>
        public static string full_copyright_notice {
            get {
                return ResourceManager.GetString("full_copyright_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No License.
        /// </summary>
        public static string full_copyright_title {
            get {
                return ResourceManager.GetString("full_copyright_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my work to be distributed and come to use, even if it carries the risk of someone I despise making changes that I despise..
        /// </summary>
        public static string no_derivatives_no {
            get {
                return ResourceManager.GetString("no_derivatives_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise uses your work in some context. They have made their own changes to your work, e.g. cut out parts, translated language, changed color, increased pacing, used it as part of a larger work, etc. You despise the changes, possibly because you feel that it misrepresents your work, or because the changes go against your aesthetic sensibilities. Do you want this to be illegal?.
        /// </summary>
        public static string no_derivatives_question {
            get {
                return ResourceManager.GetString("no_derivatives_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in order to use my work, I want them to be prevented from making changes. My work should be kept intact..
        /// </summary>
        public static string no_derivatives_yes {
            get {
                return ResourceManager.GetString("no_derivatives_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my work to be distributed and come to use, even if it carries the risk that someone I detest might use it to make money..
        /// </summary>
        public static string noncommercial_no {
            get {
                return ResourceManager.GetString("noncommercial_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise uses or distributes your work commercially. Do you want this to be illegal?.
        /// </summary>
        public static string noncommercial_question {
            get {
                return ResourceManager.GetString("noncommercial_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in order to use my work, I want them to be prevented from using it for profit..
        /// </summary>
        public static string noncommercial_yes {
            get {
                return ResourceManager.GetString("noncommercial_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example text that can be placed in combination with the work (e.g. in a book):.
        /// </summary>
        public static string notice_label {
            get {
                return ResourceManager.GetString("notice_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}:.
        /// </summary>
        public static string question_header {
            get {
                return ResourceManager.GetString("question_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I want my work to be distributed and come to use, even if it carries the risk of it becoming part of a work that is &quot;locked up&quot; behind someone else&apos;s copyright..
        /// </summary>
        public static string share_alike_no {
            get {
                return ResourceManager.GetString("share_alike_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppose someone you despise uses your work as part of their own work, or possibly uses your work directly but with modifications. They assert their full copyright in their new work, and threaten to sue anyone who uses it without permission. Do you want their use of your work to be illegal?.
        /// </summary>
        public static string share_alike_question {
            get {
                return ResourceManager.GetString("share_alike_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, in exchange for using my work, I want them to be forced to release their own work under the same conditions..
        /// </summary>
        public static string share_alike_yes {
            get {
                return ResourceManager.GetString("share_alike_yes", resourceCulture);
            }
        }
    }
}
